version: "3.8"

x-common: &common
  build:
    context: ..
    dockerfile: development/Dockerfile
  environment:
    RAILS_ENV: development
    DATABASE_URL: postgresql://postgres:password@db:5432/stripe_event_handler_development
    REDIS_URL: redis://redis:6379/0
  volumes:
    - ../:/rails-app
    - bundle:/usr/local/bundle
  depends_on:
    - db
    - redis

services:
  web:
    <<: *common
    command: rails s -p 3000 -e development -b '0.0.0.0'
    ports:
      - "3000:3000"

  test:
    <<: *common
    command: rspec
    environment:
      RAILS_ENV: test
      DATABASE_URL: postgresql://postgres:password@db:5432/stripe_event_handler_test
      REDIS_URL: redis://redis:6379/1

  sidekiq:
    <<: *common
    command: bundle exec sidekiq

  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - db:/var/lib/postgresql/data
    logging:
      driver: none
    ports:
      - 5432:5432

  redis:
    image: redis:7.4.1-alpine
    command: redis-server
    volumes:
      - redis:/data
    ports:
      - 6379
    logging:
      driver: none

volumes:
  db:
  bundle:
  redis:
