default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: stripe_event_handler_development

test:
  <<: *default
  database: stripe_event_handler_test

production:
  <<: *default
  database: stripe_event_handler_production
  username: coding_challenge
  password: <%= ENV["CODING_CHALLENGE_DATABASE_PASSWORD"] %>
