default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  database: stripe_event_handler_development

test:
  <<: *default
  url: <%= ENV['DATABASE_URL']%>
  database: stripe_event_handler_test
